version: '3.7'
services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - './backend_backup:/app/backend'
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: news_aggregator
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
